id: A736770B0
title: 'The Hook of Compassion: Calling the Guru from Afar'
type: translation
pechas:
- I7BF7CC50
- I21F958CC
- IF94CEF15
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:19.060694
  last_modified_at: 2023-01-04 12:32:19.060702
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I7BF7CC50/23D2: 8C63
  I21F958CC/90B9: 8C63
  IF94CEF15/7CE0: 8C63
